local_costmap:
  global_frame: odom
  update_frequency: 5.0
  publish_frequency: 5.0
  transform_tolerance: 1.25
  static_map: false
  rolling_window: true
  width: 3.0
  height: 3.0
  origin_x: -1.5
  origin_y: -1.5
  resolution: 0.1
  inflation_radius: 0.6

  # global_frame: odom
  # robot_base_frame: base_chassis
  # update_frequency: 10.0
  # publish_frequency: 2.0
  # static_map: false
  # rolling_window: true
  # width: 4.0
  # height: 4.0
  # resolution: 0.05
  # transform_tolerance: 0.5
  # plugins:
  #  - {name: obstacle_layer,      type: "costmap_2d::VoxelLayer"}
  #  - {name: inflation_layer,     type: "costmap_2d::InflationLayer"}